### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by sura789** [INFO-526-S24/project-01-Byte-Coders#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- [Anjani Sowmya Bollapragada] - @[asbollapragada]
- [Surajit Pal] - @[sura789]
- [Mrunal Ravindra Jadhav] - @[mrunal0699]
- [Omid Zandi] - @[zandi-omid]
- [Jeremiah Gaiser] - @[jeremiah-gaiser]
- [Praveen Kumar Pappala] - @[Praveen-Kumar-Pappala]
- ...

- Describe the goal of the project.

From the questions we do get a hint that the dataset aims to analyze the distribution and impact of Myers-Briggs personality types on character attributes across various fictional universes, focusing on correlations between personality types, character notability scores, and average ratings. It seeks to understand how personality traits influence a character's prominence and audience reception within their narrative contexts.

- Describe the data used or collected.

Three datasets are used -> character.csv, psych_stats.csv and myers_briggs.csv. These consists of features of the fictional characters across different universes and also includes their overall rating and average rating given by users. The features also include statistics about the percentage of people who matched with them and their self-identified Myers Briggs personality type.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

- The dataframe info has been provided with the variables to be used. The manipulation of data to reach the goal of the project is present, but the specific visualization techniques to be used to achieve that is not mentioned. 

- Is there anything that is unclear from the proposal?

We do get an idea of the dataset, but the choice of dataset description is abstract in few lines. The proposal also lacks clarity on visualization methods for analysis.

- Provide constructive feedback on how the team might be able to improve their project.

Please fix the formatting in the paragraphs removing star and adding new line or bullet points. Also adding of code snippets is not required. Clearly state how analyzing this dataset will make a difference or provide valuable insights. Please mention the visualization techniques you want to use.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

The analysis plan is concise and logically structured, facilitating efficient understanding. Table formatting is notably well-executed, enhancing readability and accessibility. Both aspects contribute to a streamlined and effective presentation of the data. References mentioned also provide the source of the dataset which is helpful.

- Provide constructive feedback on any issues with file and/or code organization.

Use of code snippets seems unnecessary. The first point in the choice of the dataset is very abstract. The formatting throughout the project in paragraphs having "*"  is not well constructed. Few of the points are incomplete.  The dataset seems to provide statistical insights on matching percentages and Myers Briggs personality types however, without clarity on the project's purpose and objectives, it's challenging to assess its significance or potential impact.

- (Optional) Any further comments or feedback?

**Comment by poonkundransrinivasan** [comment]
Thankyou for the informative feedback. We have already worked with all the issues mentioned and resolved them. But regarding "*" issue, We, guess you have checked the qmd file and not the actual web page as we have not mentioned "*" anywhere.
