### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by ayeshakhatunsujana** [INFO-526-S24/project-01-Byte-Coders#2]
The following is the peer review of the project proposal by [Datatude dynamos]. The team members that participated in this review are 

- Ayesha Khatun - @ayeshakhatunsujana
- Surya Vardhan Dama - @suryavardhandama
- RAJITHA REDDY TIRUTHANI - @RAJITHAREDDYTIRUTHANI
- Kamaljeet Singh - @kamaljeetsingh14
- Mrunali Yadav - @mrunaliyadavps
- Kaarthik Sai Patibandla - @zeuszapper

- Describe the goal of the project.
By employing non-traditional data analytic techniques to examine the personality features of fictional characters from many pop culture worlds, the project seeks to investigate the relationship between psychology and popular culture.

- Describe the data used or collected.
About 890 characters from 100 distinct universes make up the data. Some of the files are 'character.csv', which contains links to character information and pictures, notability scores, and character names; 'psych_stats.csv', which contains personality traits, ratings, ranks, and standard deviations; and'myers_briggs.csv', which provides information on Myers-Briggs personality types and match percentages.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
In order to answer the goals of the research, data from several data frames will be combined and grouped according to common identifiers such as character ID, universe name, and personality qualities. Statistical analysis will then be performed to look for patterns, correlations, and variances in the data.

- Is there anything that is unclear from the proposal?
For both questions, as you are not mention data preparation process as well as data analysis technique, that's why the proposal is not clear that much. Introduction, approach and discussion section also missing in questions analysis section.  The definition and calculation of notability scores, as well as its relationship to the personality qualities and Myers-Briggs types of the characters, are not totally clear.

- Provide constructive feedback on how the team might be able to improve their project.
A more precise description of important words like "average match percentage" and "notability scores" will be beneficial for the project. The analysis might also be improved by adding visualizations to show the relationships and distributions of the data.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
Of particular interest is the relationship between character notability scores and Myers-Briggs personality types within universes, which could provide insights into the factors that contribute to the notoriety or relatability of particular personality types in popular culture.

- Provide constructive feedback on any issues with file and/or code organization.
We think that they should add introduction and discussion section in every questions.  In the data folder they need to add dataset.csv file. In README file you have to upload the description of the dataset.  At the beginning of website adding ("pacman") code is not necessary. Make sure the code is well-structured and documented, with comments that clearly describe each stage of the data cleaning, analysis, and merging procedures. Readability can also be improved by using uniform naming conventions for variables and data frames.

-  (Optional) Any further comments or feedback?
It's good that you added the references. But a qualitative study or professional perspectives on certain characters or worlds could add depth to the findings, especially in cases where the data may not fully reflect the richness of personality traits, given the uniqueness of analyzing fictitious characters.

**Comment by poonkundransrinivasan** [comment]
Thankyou for the informative feedback. All the issues has been addressed and updated. Regarding the absence of actual csv file in the data folder, we have used the raw link for the dataset and therefore, the information of the dataset such as datatypes and descriptions of the attributes have been mentioned in the proposal.
