### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-S24/project-01-Byte-Coders#3]
Dear Byte-Coders: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |    3    |
| Proposal | 5         |    4.75    |
| Workflow | 1         |   1     |
| Teamwork | 1         |    1    |
| Total    | 10        |    9.75    |

**Feedback**: 
Pretty close to perfect. I am only missing a timeline of when things will be complete. Your proposal was pretty thorough, so I only took off a relatively small amount for this.

**Comment by Gchism94** [comment]
You probably don't need one, but if you would like a regrade, please address and resubmit your proposal by **Monday, Feb 19th, 11:59pm**.

**Procedure**

1. Close this issue.
2. Open a new blank one requesting a regrade

Your final score will be the midpoint between the two scores.

**Comment by ayeshakhatunsujana** [comment]
Thank you for your feedback!

**Comment by ayeshakhatunsujana** [comment]
Can't find any close issue button!!!
