### ISSUE TITLE
Presentation peer review - GraphCraphters

### ISSUE THREAD

**Issue by asbollapragada** [INFO-526-S24/project-01-Byte-Coders#4]
The following is the peer review of the Presentation proposal by GraphCraphters. The team members who participated in this review are 

- [Anjani Sowmya Bollapragada] - @[asbollapragada]
- [Surajit Pal] - @[sura789]
- [Mrunal Ravindra Jadhav] - @[mrunal0699]
- [Omid Zandi] - @[zandi-omid]
- [Jeremiah Gaiser] - @[jeremiah-gaiser]
- [Praveen Kumar Pappala] - @[Praveen-Kumar-Pappala]

- Content: Is the research question well designed and is the data being used relevant to the research question?

Yes, the research question is well-designed and the data being used is relevant to the question.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

The visualizations are good, especially plot 3 of question 1. However, the plot 1 of question 1 can be simplified and made easy to understand. Could have more variations in the visualizations rather than focusing on variations in bar plots.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

Yes, the project was carefully thought out and the questions were organized properly. Considering question 1, finding insights into personality traits between Myers-Briggs with all other characters seems to take a lot of effort which was well executed.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Although the slides are well organized, readable (except for plot 1 of question 1), and feature figures with legible labels, the presentation has more text as well in a few areas,

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

Yes, the team presented well. The presentation appeared to be well-practiced. Everyone got a chance to say something meaningful about the project.

**Comment by poonkundransrinivasan** [comment]
Thankyou for the valuable feedback
