### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by RAJITHAREDDYTIRUTHANI** [INFO-526-S24/project-01-Byte-Coders#5]
The following is the peer review of the Presentation proposal by Datatude-dynamos. The team members that participated in this review are 

- Surya Vardhan Dama - @suryavardhandama
- Ayesha Khatun - @ayeshakhatunsujana
- Kamaljeet Singh - @kamaljeetsingh14
-  Mrunali Yadav - @mrunaliyadavps
- Kaarthik Sai Patibandla - @zeuszapper
- Rajitha Reddy Tiruthani - @RAJITHAREDDYTIRUTHANI

- Content: Is the research question well designed and is the data being used relevant to the research question?

    Yes, The examination of research questions appears well organized, but you have forgotten to explain about the notability score.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Your team's  presentation visualizations of all the plots are interesting and are accurately interpreted. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
You have made your plots in a creative way and structured in a proper manner. I think for the Mainly for the first question, i can see your efforts and strong planning which created great implementation of the project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
You did a fantastic job arranging your presentation. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
In the presentation, every member of your team did outstanding work.

**Comment by poonkundransrinivasan** [comment]
Thankyou for the valuable feedback
